const Constants = {
    GET_ALL_EMPLOYEE_SUCESS: "GET_ALL_EMPLOYEE_SUCESS",
    GET_EMPLOYEE_BY_ID_SUCESS: "GET_EMPLOYEE_BY_ID_SUCESS",
    ADD_EMPLOYEE_SUCESS: "ADD_EMPLOYEE_SUCESS",
    UPDATE_EMPLOYEE_SUCESS: "UPDATE_EMPLOYEE_SUCESS",
    REMOVE_EMPLOYEE_SUCESS: "REMOVE_EMPLOYEE_SUCESS",

    GET_ALL_DEPARTMENT_SUCESS: "GET_ALL_DEPARTMENT_SUCESS",
    GET_DEPARTMENT_BY_ID_SUCESS: "GET_DEPARTMENT_BY_ID_SUCESS",
    ADD_DEPARTMENT_SUCESS: "ADD_DEPARTMENT_SUCESS",
    UPDATE_DEPARTMENT_SUCESS: "UPDATE_DEPARTMENT_SUCESS",
    REMOVE_DEPARTMENT_SUCESS: "REMOVE_DEPARTMENT_SUCESS",
}

export default Constants 